name: Lint and Test (Push)

on:
  push:
    branches:
      - '**'  # Run on push to any branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ruff linter
      run: |
        ruff check .
      continue-on-error: false  # Fail the build if linting fails

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "test_*.py" -v
